# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/webpack-mdns

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/webpack-mdns

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/webpack-mdns/CMakeFiles /root/webpack-mdns/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/webpack-mdns/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mdns-controller

# Build rule for target.
mdns-controller: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mdns-controller
.PHONY : mdns-controller

# fast build rule for target.
mdns-controller/fast:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/build
.PHONY : mdns-controller/fast

#=============================================================================
# Target rules for targets named absl_exponential_biased

# Build rule for target.
absl_exponential_biased: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_exponential_biased
.PHONY : absl_exponential_biased

# fast build rule for target.
absl_exponential_biased/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_exponential_biased.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_exponential_biased.dir/build
.PHONY : absl_exponential_biased/fast

#=============================================================================
# Target rules for targets named absl_strerror

# Build rule for target.
absl_strerror: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_strerror
.PHONY : absl_strerror

# fast build rule for target.
absl_strerror/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_strerror.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_strerror.dir/build
.PHONY : absl_strerror/fast

#=============================================================================
# Target rules for targets named absl_spinlock_wait

# Build rule for target.
absl_spinlock_wait: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_spinlock_wait
.PHONY : absl_spinlock_wait

# fast build rule for target.
absl_spinlock_wait/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/build
.PHONY : absl_spinlock_wait/fast

#=============================================================================
# Target rules for targets named absl_raw_logging_internal

# Build rule for target.
absl_raw_logging_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_raw_logging_internal
.PHONY : absl_raw_logging_internal

# fast build rule for target.
absl_raw_logging_internal/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_raw_logging_internal.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_raw_logging_internal.dir/build
.PHONY : absl_raw_logging_internal/fast

#=============================================================================
# Target rules for targets named absl_throw_delegate

# Build rule for target.
absl_throw_delegate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_throw_delegate
.PHONY : absl_throw_delegate

# fast build rule for target.
absl_throw_delegate/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_throw_delegate.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_throw_delegate.dir/build
.PHONY : absl_throw_delegate/fast

#=============================================================================
# Target rules for targets named absl_periodic_sampler

# Build rule for target.
absl_periodic_sampler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_periodic_sampler
.PHONY : absl_periodic_sampler

# fast build rule for target.
absl_periodic_sampler/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_periodic_sampler.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_periodic_sampler.dir/build
.PHONY : absl_periodic_sampler/fast

#=============================================================================
# Target rules for targets named absl_log_severity

# Build rule for target.
absl_log_severity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_log_severity
.PHONY : absl_log_severity

# fast build rule for target.
absl_log_severity/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/build
.PHONY : absl_log_severity/fast

#=============================================================================
# Target rules for targets named absl_malloc_internal

# Build rule for target.
absl_malloc_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_malloc_internal
.PHONY : absl_malloc_internal

# fast build rule for target.
absl_malloc_internal/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build
.PHONY : absl_malloc_internal/fast

#=============================================================================
# Target rules for targets named absl_scoped_set_env

# Build rule for target.
absl_scoped_set_env: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_scoped_set_env
.PHONY : absl_scoped_set_env

# fast build rule for target.
absl_scoped_set_env/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_scoped_set_env.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_scoped_set_env.dir/build
.PHONY : absl_scoped_set_env/fast

#=============================================================================
# Target rules for targets named absl_base

# Build rule for target.
absl_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_base
.PHONY : absl_base

# fast build rule for target.
absl_base/fast:
	$(MAKE) -f abseil-cpp/absl/base/CMakeFiles/absl_base.dir/build.make abseil-cpp/absl/base/CMakeFiles/absl_base.dir/build
.PHONY : absl_base/fast

#=============================================================================
# Target rules for targets named absl_raw_hash_set

# Build rule for target.
absl_raw_hash_set: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_raw_hash_set
.PHONY : absl_raw_hash_set

# fast build rule for target.
absl_raw_hash_set/fast:
	$(MAKE) -f abseil-cpp/absl/container/CMakeFiles/absl_raw_hash_set.dir/build.make abseil-cpp/absl/container/CMakeFiles/absl_raw_hash_set.dir/build
.PHONY : absl_raw_hash_set/fast

#=============================================================================
# Target rules for targets named absl_hashtablez_sampler

# Build rule for target.
absl_hashtablez_sampler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_hashtablez_sampler
.PHONY : absl_hashtablez_sampler

# fast build rule for target.
absl_hashtablez_sampler/fast:
	$(MAKE) -f abseil-cpp/absl/container/CMakeFiles/absl_hashtablez_sampler.dir/build.make abseil-cpp/absl/container/CMakeFiles/absl_hashtablez_sampler.dir/build
.PHONY : absl_hashtablez_sampler/fast

#=============================================================================
# Target rules for targets named absl_stacktrace

# Build rule for target.
absl_stacktrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_stacktrace
.PHONY : absl_stacktrace

# fast build rule for target.
absl_stacktrace/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_stacktrace.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_stacktrace.dir/build
.PHONY : absl_stacktrace/fast

#=============================================================================
# Target rules for targets named absl_symbolize

# Build rule for target.
absl_symbolize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_symbolize
.PHONY : absl_symbolize

# fast build rule for target.
absl_symbolize/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_symbolize.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_symbolize.dir/build
.PHONY : absl_symbolize/fast

#=============================================================================
# Target rules for targets named absl_failure_signal_handler

# Build rule for target.
absl_failure_signal_handler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_failure_signal_handler
.PHONY : absl_failure_signal_handler

# fast build rule for target.
absl_failure_signal_handler/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_failure_signal_handler.dir/build
.PHONY : absl_failure_signal_handler/fast

#=============================================================================
# Target rules for targets named absl_debugging_internal

# Build rule for target.
absl_debugging_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_debugging_internal
.PHONY : absl_debugging_internal

# fast build rule for target.
absl_debugging_internal/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_debugging_internal.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_debugging_internal.dir/build
.PHONY : absl_debugging_internal/fast

#=============================================================================
# Target rules for targets named absl_demangle_internal

# Build rule for target.
absl_demangle_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_demangle_internal
.PHONY : absl_demangle_internal

# fast build rule for target.
absl_demangle_internal/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_demangle_internal.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_demangle_internal.dir/build
.PHONY : absl_demangle_internal/fast

#=============================================================================
# Target rules for targets named absl_leak_check

# Build rule for target.
absl_leak_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_leak_check
.PHONY : absl_leak_check

# fast build rule for target.
absl_leak_check/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check.dir/build
.PHONY : absl_leak_check/fast

#=============================================================================
# Target rules for targets named absl_leak_check_disable

# Build rule for target.
absl_leak_check_disable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_leak_check_disable
.PHONY : absl_leak_check_disable

# fast build rule for target.
absl_leak_check_disable/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check_disable.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check_disable.dir/build
.PHONY : absl_leak_check_disable/fast

#=============================================================================
# Target rules for targets named absl_examine_stack

# Build rule for target.
absl_examine_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_examine_stack
.PHONY : absl_examine_stack

# fast build rule for target.
absl_examine_stack/fast:
	$(MAKE) -f abseil-cpp/absl/debugging/CMakeFiles/absl_examine_stack.dir/build.make abseil-cpp/absl/debugging/CMakeFiles/absl_examine_stack.dir/build
.PHONY : absl_examine_stack/fast

#=============================================================================
# Target rules for targets named absl_flags_program_name

# Build rule for target.
absl_flags_program_name: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_program_name
.PHONY : absl_flags_program_name

# fast build rule for target.
absl_flags_program_name/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_program_name.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_program_name.dir/build
.PHONY : absl_flags_program_name/fast

#=============================================================================
# Target rules for targets named absl_flags_reflection

# Build rule for target.
absl_flags_reflection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_reflection
.PHONY : absl_flags_reflection

# fast build rule for target.
absl_flags_reflection/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_reflection.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_reflection.dir/build
.PHONY : absl_flags_reflection/fast

#=============================================================================
# Target rules for targets named absl_flags_config

# Build rule for target.
absl_flags_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_config
.PHONY : absl_flags_config

# fast build rule for target.
absl_flags_config/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_config.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_config.dir/build
.PHONY : absl_flags_config/fast

#=============================================================================
# Target rules for targets named absl_flags_private_handle_accessor

# Build rule for target.
absl_flags_private_handle_accessor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_private_handle_accessor
.PHONY : absl_flags_private_handle_accessor

# fast build rule for target.
absl_flags_private_handle_accessor/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_private_handle_accessor.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_private_handle_accessor.dir/build
.PHONY : absl_flags_private_handle_accessor/fast

#=============================================================================
# Target rules for targets named absl_flags_marshalling

# Build rule for target.
absl_flags_marshalling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_marshalling
.PHONY : absl_flags_marshalling

# fast build rule for target.
absl_flags_marshalling/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_marshalling.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_marshalling.dir/build
.PHONY : absl_flags_marshalling/fast

#=============================================================================
# Target rules for targets named absl_flags

# Build rule for target.
absl_flags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags
.PHONY : absl_flags

# fast build rule for target.
absl_flags/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags.dir/build
.PHONY : absl_flags/fast

#=============================================================================
# Target rules for targets named absl_flags_commandlineflag_internal

# Build rule for target.
absl_flags_commandlineflag_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_commandlineflag_internal
.PHONY : absl_flags_commandlineflag_internal

# fast build rule for target.
absl_flags_commandlineflag_internal/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag_internal.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag_internal.dir/build
.PHONY : absl_flags_commandlineflag_internal/fast

#=============================================================================
# Target rules for targets named absl_flags_commandlineflag

# Build rule for target.
absl_flags_commandlineflag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_commandlineflag
.PHONY : absl_flags_commandlineflag

# fast build rule for target.
absl_flags_commandlineflag/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag.dir/build
.PHONY : absl_flags_commandlineflag/fast

#=============================================================================
# Target rules for targets named absl_flags_internal

# Build rule for target.
absl_flags_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_internal
.PHONY : absl_flags_internal

# fast build rule for target.
absl_flags_internal/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_internal.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_internal.dir/build
.PHONY : absl_flags_internal/fast

#=============================================================================
# Target rules for targets named absl_flags_parse

# Build rule for target.
absl_flags_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_parse
.PHONY : absl_flags_parse

# fast build rule for target.
absl_flags_parse/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_parse.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_parse.dir/build
.PHONY : absl_flags_parse/fast

#=============================================================================
# Target rules for targets named absl_flags_usage_internal

# Build rule for target.
absl_flags_usage_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_usage_internal
.PHONY : absl_flags_usage_internal

# fast build rule for target.
absl_flags_usage_internal/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_usage_internal.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_usage_internal.dir/build
.PHONY : absl_flags_usage_internal/fast

#=============================================================================
# Target rules for targets named absl_flags_usage

# Build rule for target.
absl_flags_usage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_flags_usage
.PHONY : absl_flags_usage

# fast build rule for target.
absl_flags_usage/fast:
	$(MAKE) -f abseil-cpp/absl/flags/CMakeFiles/absl_flags_usage.dir/build.make abseil-cpp/absl/flags/CMakeFiles/absl_flags_usage.dir/build
.PHONY : absl_flags_usage/fast

#=============================================================================
# Target rules for targets named absl_city

# Build rule for target.
absl_city: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_city
.PHONY : absl_city

# fast build rule for target.
absl_city/fast:
	$(MAKE) -f abseil-cpp/absl/hash/CMakeFiles/absl_city.dir/build.make abseil-cpp/absl/hash/CMakeFiles/absl_city.dir/build
.PHONY : absl_city/fast

#=============================================================================
# Target rules for targets named absl_hash

# Build rule for target.
absl_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_hash
.PHONY : absl_hash

# fast build rule for target.
absl_hash/fast:
	$(MAKE) -f abseil-cpp/absl/hash/CMakeFiles/absl_hash.dir/build.make abseil-cpp/absl/hash/CMakeFiles/absl_hash.dir/build
.PHONY : absl_hash/fast

#=============================================================================
# Target rules for targets named absl_int128

# Build rule for target.
absl_int128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_int128
.PHONY : absl_int128

# fast build rule for target.
absl_int128/fast:
	$(MAKE) -f abseil-cpp/absl/numeric/CMakeFiles/absl_int128.dir/build.make abseil-cpp/absl/numeric/CMakeFiles/absl_int128.dir/build
.PHONY : absl_int128/fast

#=============================================================================
# Target rules for targets named absl_random_internal_pool_urbg

# Build rule for target.
absl_random_internal_pool_urbg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_pool_urbg
.PHONY : absl_random_internal_pool_urbg

# fast build rule for target.
absl_random_internal_pool_urbg/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_pool_urbg.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_pool_urbg.dir/build
.PHONY : absl_random_internal_pool_urbg/fast

#=============================================================================
# Target rules for targets named absl_random_distributions

# Build rule for target.
absl_random_distributions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_distributions
.PHONY : absl_random_distributions

# fast build rule for target.
absl_random_distributions/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_distributions.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_distributions.dir/build
.PHONY : absl_random_distributions/fast

#=============================================================================
# Target rules for targets named absl_random_seed_gen_exception

# Build rule for target.
absl_random_seed_gen_exception: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_seed_gen_exception
.PHONY : absl_random_seed_gen_exception

# fast build rule for target.
absl_random_seed_gen_exception/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_seed_gen_exception.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_seed_gen_exception.dir/build
.PHONY : absl_random_seed_gen_exception/fast

#=============================================================================
# Target rules for targets named absl_random_seed_sequences

# Build rule for target.
absl_random_seed_sequences: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_seed_sequences
.PHONY : absl_random_seed_sequences

# fast build rule for target.
absl_random_seed_sequences/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_seed_sequences.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_seed_sequences.dir/build
.PHONY : absl_random_seed_sequences/fast

#=============================================================================
# Target rules for targets named absl_random_internal_distribution_test_util

# Build rule for target.
absl_random_internal_distribution_test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_distribution_test_util
.PHONY : absl_random_internal_distribution_test_util

# fast build rule for target.
absl_random_internal_distribution_test_util/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_distribution_test_util.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_distribution_test_util.dir/build
.PHONY : absl_random_internal_distribution_test_util/fast

#=============================================================================
# Target rules for targets named absl_random_internal_seed_material

# Build rule for target.
absl_random_internal_seed_material: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_seed_material
.PHONY : absl_random_internal_seed_material

# fast build rule for target.
absl_random_internal_seed_material/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_seed_material.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_seed_material.dir/build
.PHONY : absl_random_internal_seed_material/fast

#=============================================================================
# Target rules for targets named absl_random_internal_randen_slow

# Build rule for target.
absl_random_internal_randen_slow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_randen_slow
.PHONY : absl_random_internal_randen_slow

# fast build rule for target.
absl_random_internal_randen_slow/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_slow.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_slow.dir/build
.PHONY : absl_random_internal_randen_slow/fast

#=============================================================================
# Target rules for targets named absl_random_internal_platform

# Build rule for target.
absl_random_internal_platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_platform
.PHONY : absl_random_internal_platform

# fast build rule for target.
absl_random_internal_platform/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_platform.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_platform.dir/build
.PHONY : absl_random_internal_platform/fast

#=============================================================================
# Target rules for targets named absl_random_internal_randen

# Build rule for target.
absl_random_internal_randen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_randen
.PHONY : absl_random_internal_randen

# fast build rule for target.
absl_random_internal_randen/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen.dir/build
.PHONY : absl_random_internal_randen/fast

#=============================================================================
# Target rules for targets named absl_random_internal_randen_hwaes

# Build rule for target.
absl_random_internal_randen_hwaes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_randen_hwaes
.PHONY : absl_random_internal_randen_hwaes

# fast build rule for target.
absl_random_internal_randen_hwaes/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes.dir/build
.PHONY : absl_random_internal_randen_hwaes/fast

#=============================================================================
# Target rules for targets named absl_random_internal_randen_hwaes_impl

# Build rule for target.
absl_random_internal_randen_hwaes_impl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_random_internal_randen_hwaes_impl
.PHONY : absl_random_internal_randen_hwaes_impl

# fast build rule for target.
absl_random_internal_randen_hwaes_impl/fast:
	$(MAKE) -f abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/build.make abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/build
.PHONY : absl_random_internal_randen_hwaes_impl/fast

#=============================================================================
# Target rules for targets named absl_statusor

# Build rule for target.
absl_statusor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_statusor
.PHONY : absl_statusor

# fast build rule for target.
absl_statusor/fast:
	$(MAKE) -f abseil-cpp/absl/status/CMakeFiles/absl_statusor.dir/build.make abseil-cpp/absl/status/CMakeFiles/absl_statusor.dir/build
.PHONY : absl_statusor/fast

#=============================================================================
# Target rules for targets named absl_status

# Build rule for target.
absl_status: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_status
.PHONY : absl_status

# fast build rule for target.
absl_status/fast:
	$(MAKE) -f abseil-cpp/absl/status/CMakeFiles/absl_status.dir/build.make abseil-cpp/absl/status/CMakeFiles/absl_status.dir/build
.PHONY : absl_status/fast

#=============================================================================
# Target rules for targets named absl_str_format_internal

# Build rule for target.
absl_str_format_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_str_format_internal
.PHONY : absl_str_format_internal

# fast build rule for target.
absl_str_format_internal/fast:
	$(MAKE) -f abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/build.make abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/build
.PHONY : absl_str_format_internal/fast

#=============================================================================
# Target rules for targets named absl_strings_internal

# Build rule for target.
absl_strings_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_strings_internal
.PHONY : absl_strings_internal

# fast build rule for target.
absl_strings_internal/fast:
	$(MAKE) -f abseil-cpp/absl/strings/CMakeFiles/absl_strings_internal.dir/build.make abseil-cpp/absl/strings/CMakeFiles/absl_strings_internal.dir/build
.PHONY : absl_strings_internal/fast

#=============================================================================
# Target rules for targets named absl_cord

# Build rule for target.
absl_cord: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_cord
.PHONY : absl_cord

# fast build rule for target.
absl_cord/fast:
	$(MAKE) -f abseil-cpp/absl/strings/CMakeFiles/absl_cord.dir/build.make abseil-cpp/absl/strings/CMakeFiles/absl_cord.dir/build
.PHONY : absl_cord/fast

#=============================================================================
# Target rules for targets named absl_strings

# Build rule for target.
absl_strings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_strings
.PHONY : absl_strings

# fast build rule for target.
absl_strings/fast:
	$(MAKE) -f abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/build.make abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/build
.PHONY : absl_strings/fast

#=============================================================================
# Target rules for targets named absl_synchronization

# Build rule for target.
absl_synchronization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_synchronization
.PHONY : absl_synchronization

# fast build rule for target.
absl_synchronization/fast:
	$(MAKE) -f abseil-cpp/absl/synchronization/CMakeFiles/absl_synchronization.dir/build.make abseil-cpp/absl/synchronization/CMakeFiles/absl_synchronization.dir/build
.PHONY : absl_synchronization/fast

#=============================================================================
# Target rules for targets named absl_graphcycles_internal

# Build rule for target.
absl_graphcycles_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_graphcycles_internal
.PHONY : absl_graphcycles_internal

# fast build rule for target.
absl_graphcycles_internal/fast:
	$(MAKE) -f abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/build.make abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/build
.PHONY : absl_graphcycles_internal/fast

#=============================================================================
# Target rules for targets named absl_time_zone

# Build rule for target.
absl_time_zone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_time_zone
.PHONY : absl_time_zone

# fast build rule for target.
absl_time_zone/fast:
	$(MAKE) -f abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/build.make abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/build
.PHONY : absl_time_zone/fast

#=============================================================================
# Target rules for targets named absl_civil_time

# Build rule for target.
absl_civil_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_civil_time
.PHONY : absl_civil_time

# fast build rule for target.
absl_civil_time/fast:
	$(MAKE) -f abseil-cpp/absl/time/CMakeFiles/absl_civil_time.dir/build.make abseil-cpp/absl/time/CMakeFiles/absl_civil_time.dir/build
.PHONY : absl_civil_time/fast

#=============================================================================
# Target rules for targets named absl_time

# Build rule for target.
absl_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_time
.PHONY : absl_time

# fast build rule for target.
absl_time/fast:
	$(MAKE) -f abseil-cpp/absl/time/CMakeFiles/absl_time.dir/build.make abseil-cpp/absl/time/CMakeFiles/absl_time.dir/build
.PHONY : absl_time/fast

#=============================================================================
# Target rules for targets named absl_bad_any_cast_impl

# Build rule for target.
absl_bad_any_cast_impl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_bad_any_cast_impl
.PHONY : absl_bad_any_cast_impl

# fast build rule for target.
absl_bad_any_cast_impl/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_bad_any_cast_impl.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_bad_any_cast_impl.dir/build
.PHONY : absl_bad_any_cast_impl/fast

#=============================================================================
# Target rules for targets named absl_bad_optional_access

# Build rule for target.
absl_bad_optional_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_bad_optional_access
.PHONY : absl_bad_optional_access

# fast build rule for target.
absl_bad_optional_access/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_bad_optional_access.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_bad_optional_access.dir/build
.PHONY : absl_bad_optional_access/fast

#=============================================================================
# Target rules for targets named absl_bad_variant_access

# Build rule for target.
absl_bad_variant_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 absl_bad_variant_access
.PHONY : absl_bad_variant_access

# fast build rule for target.
absl_bad_variant_access/fast:
	$(MAKE) -f abseil-cpp/absl/types/CMakeFiles/absl_bad_variant_access.dir/build.make abseil-cpp/absl/types/CMakeFiles/absl_bad_variant_access.dir/build
.PHONY : absl_bad_variant_access/fast

#=============================================================================
# Target rules for targets named mdns_example

# Build rule for target.
mdns_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mdns_example
.PHONY : mdns_example

# fast build rule for target.
mdns_example/fast:
	$(MAKE) -f mdns/CMakeFiles/mdns_example.dir/build.make mdns/CMakeFiles/mdns_example.dir/build
.PHONY : mdns_example/fast

NetworkController.o: NetworkController.cpp.o

.PHONY : NetworkController.o

# target to build an object file
NetworkController.cpp.o:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/NetworkController.cpp.o
.PHONY : NetworkController.cpp.o

NetworkController.i: NetworkController.cpp.i

.PHONY : NetworkController.i

# target to preprocess a source file
NetworkController.cpp.i:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/NetworkController.cpp.i
.PHONY : NetworkController.cpp.i

NetworkController.s: NetworkController.cpp.s

.PHONY : NetworkController.s

# target to generate assembly for a file
NetworkController.cpp.s:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/NetworkController.cpp.s
.PHONY : NetworkController.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mdns-controller.dir/build.make CMakeFiles/mdns-controller.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mdns-controller"
	@echo "... absl_exponential_biased"
	@echo "... absl_strerror"
	@echo "... absl_spinlock_wait"
	@echo "... absl_raw_logging_internal"
	@echo "... absl_throw_delegate"
	@echo "... absl_periodic_sampler"
	@echo "... absl_log_severity"
	@echo "... absl_malloc_internal"
	@echo "... absl_scoped_set_env"
	@echo "... absl_base"
	@echo "... absl_raw_hash_set"
	@echo "... absl_hashtablez_sampler"
	@echo "... absl_stacktrace"
	@echo "... absl_symbolize"
	@echo "... absl_failure_signal_handler"
	@echo "... absl_debugging_internal"
	@echo "... absl_demangle_internal"
	@echo "... absl_leak_check"
	@echo "... absl_leak_check_disable"
	@echo "... absl_examine_stack"
	@echo "... absl_flags_program_name"
	@echo "... absl_flags_reflection"
	@echo "... absl_flags_config"
	@echo "... absl_flags_private_handle_accessor"
	@echo "... absl_flags_marshalling"
	@echo "... absl_flags"
	@echo "... absl_flags_commandlineflag_internal"
	@echo "... absl_flags_commandlineflag"
	@echo "... absl_flags_internal"
	@echo "... absl_flags_parse"
	@echo "... absl_flags_usage_internal"
	@echo "... absl_flags_usage"
	@echo "... absl_city"
	@echo "... absl_hash"
	@echo "... absl_int128"
	@echo "... absl_random_internal_pool_urbg"
	@echo "... absl_random_distributions"
	@echo "... absl_random_seed_gen_exception"
	@echo "... absl_random_seed_sequences"
	@echo "... absl_random_internal_distribution_test_util"
	@echo "... absl_random_internal_seed_material"
	@echo "... absl_random_internal_randen_slow"
	@echo "... absl_random_internal_platform"
	@echo "... absl_random_internal_randen"
	@echo "... absl_random_internal_randen_hwaes"
	@echo "... absl_random_internal_randen_hwaes_impl"
	@echo "... absl_statusor"
	@echo "... absl_status"
	@echo "... absl_str_format_internal"
	@echo "... absl_strings_internal"
	@echo "... absl_cord"
	@echo "... absl_strings"
	@echo "... absl_synchronization"
	@echo "... absl_graphcycles_internal"
	@echo "... absl_time_zone"
	@echo "... absl_civil_time"
	@echo "... absl_time"
	@echo "... absl_bad_any_cast_impl"
	@echo "... absl_bad_optional_access"
	@echo "... absl_bad_variant_access"
	@echo "... mdns_example"
	@echo "... NetworkController.o"
	@echo "... NetworkController.i"
	@echo "... NetworkController.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

